services:
  - type: web
    name: my-flask-app
    env: python
    region: oregon
    plan: free
    buildCommand:  |
      pip install -r requirements.txt
      flask db migrate -m "Add wave_number to UserChoice"
      flask db upgrade
    startCommand: gunicorn app:app
