services:
  - type: web
    name: my-flask-app
    env: python
    region: oregon
    plan: free
    buildCommand:  |
    pip install -r requirements.txt
    flask db init
    flask db migrate -m "Initial migration."
    flask db upgrate
    startCommand: gunicorn app:app
