services:
  - type: web
    name: my-flask-app
    env: python
    region: oregon
    plan: free
    buildCommand:  |
    pip install -r requirements.txt
    python migration_script.py
    startCommand: gunicorn app:app
